// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn6ysm55u1IINOe-mJdufT5lUmHM3cPs8',
    appId: '1:300221867879:web:6b137ab934d0456989b1c2',
    messagingSenderId: '300221867879',
    projectId: 'legacy-keeper-88d55',
    authDomain: 'legacy-keeper-88d55.firebaseapp.com',
    storageBucket: 'legacy-keeper-88d55.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOVGYNO31jPlAJXoihE5ExDB9-6H3FqX8',
    appId: '1:300221867879:android:a2db6370b6fe1f3b89b1c2',
    messagingSenderId: '300221867879',
    projectId: 'legacy-keeper-88d55',
    storageBucket: 'legacy-keeper-88d55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5XLVwFkaTXO8-sxo_Z8vOgkz2TlR5kjI',
    appId: '1:300221867879:ios:0153437ceed392e589b1c2',
    messagingSenderId: '300221867879',
    projectId: 'legacy-keeper-88d55',
    storageBucket: 'legacy-keeper-88d55.firebasestorage.app',
    iosBundleId: 'com.example.legacyKeeper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5XLVwFkaTXO8-sxo_Z8vOgkz2TlR5kjI',
    appId: '1:300221867879:ios:0153437ceed392e589b1c2',
    messagingSenderId: '300221867879',
    projectId: 'legacy-keeper-88d55',
    storageBucket: 'legacy-keeper-88d55.firebasestorage.app',
    iosBundleId: 'com.example.legacyKeeper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn6ysm55u1IINOe-mJdufT5lUmHM3cPs8',
    appId: '1:300221867879:web:e483ac01b053707989b1c2',
    messagingSenderId: '300221867879',
    projectId: 'legacy-keeper-88d55',
    authDomain: 'legacy-keeper-88d55.firebaseapp.com',
    storageBucket: 'legacy-keeper-88d55.firebasestorage.app',
  );
}
